// <auto-generated />
using System;
using DossierAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DossierAPI.Migrations
{
    [DbContext(typeof(DossierContext))]
    partial class DossierContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("DossierAPI.Models.Billet", b =>
                {
                    b.Property<Guid>("IdBillet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VolId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdBillet");

                    b.HasIndex("ReservationId");

                    b.ToTable("Billets");
                });

            modelBuilder.Entity("DossierAPI.Models.Categorie", b =>
                {
                    b.Property<Guid>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeCategorie")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCategorie");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DossierAPI.Models.Client", b =>
                {
                    b.Property<Guid>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DossierAPI.Models.Compagnie", b =>
                {
                    b.Property<Guid>("IdCompagnie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomCompagnie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pays")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCompagnie");

                    b.ToTable("Compagnies");
                });

            modelBuilder.Entity("DossierAPI.Models.Reservation", b =>
                {
                    b.Property<Guid>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateReservationVol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdReservation");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DossierAPI.Models.Vol", b =>
                {
                    b.Property<Guid>("IdVol")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompagnieIdCompagnie")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanieId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Prix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdVol");

                    b.HasIndex("CompagnieIdCompagnie");

                    b.ToTable("Vols");
                });

            modelBuilder.Entity("DossierAPI.Models.Billet", b =>
                {
                    b.HasOne("DossierAPI.Models.Reservation", null)
                        .WithMany("Billets")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DossierAPI.Models.Vol", b =>
                {
                    b.HasOne("DossierAPI.Models.Compagnie", null)
                        .WithMany("Vols")
                        .HasForeignKey("CompagnieIdCompagnie");
                });

            modelBuilder.Entity("DossierAPI.Models.Compagnie", b =>
                {
                    b.Navigation("Vols");
                });

            modelBuilder.Entity("DossierAPI.Models.Reservation", b =>
                {
                    b.Navigation("Billets");
                });
#pragma warning restore 612, 618
        }
    }
}
